
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josem
 */
public class inicio extends javax.swing.JFrame {
    Map<String, String> usuariosRegistrados = new HashMap();
    Map<String, String> usuariosAdministradores = new HashMap();
    Map<String, Boolean> carrosPortatiles = new HashMap();
    int numCarrosD = 0;
    int numCarrosND = 0;

    String usuario = "";
    String password = "";
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        // AGREGAMOS LOS USUARIOS MANUALMENTE QUE SERÁN REGISTRADOS 
        usuariosRegistrados.put("jesus", "jesus");
        usuariosRegistrados.put("manolo", "manolo");
        /**
         * AGREGAMOS LOS CARROS CON SU CÓDIGO DE CARRO Y SI ESTA DISPONIBLE O NO
         *      false -> EL CARRO NO ESTÁ DISPONIBLE PARA SER ALQUILADO
         *      true --> EL CARRO SÍ ESTÁ DISPONIBLE PARA SER ALQUILADO
         */
        carrosPortatiles.put("1", true);
        carrosPortatiles.put("2", true);
        carrosPortatiles.put("3", true);
        carrosPortatiles.put("4", true);
        
        /**
         * AGREGAMOS LOS USUARIOS ADMINISTRADORES
         */
        usuariosAdministradores.put("admin", "admin");
        usuariosAdministradores.put("root", "root");

        

    }
    
    public inicio(int numCarros) {
        initComponents();
        numCarrosD = numCarros;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonLogin = new javax.swing.JButton();
        botonCarrosDisponibles = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARROS DE PORTÁTILES");

        botonLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonLogin.setForeground(new java.awt.Color(255, 0, 0));
        botonLogin.setText("LOG IN");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        botonCarrosDisponibles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonCarrosDisponibles.setForeground(new java.awt.Color(255, 0, 0));
        botonCarrosDisponibles.setText("VER CARROS DISPONIBLES");
        botonCarrosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarrosDisponiblesActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("SOLICITAR ALTA USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCarrosDisponibles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(botonCarrosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        int tamCarros = carrosPortatiles.size();
        // CONTADOR DEL BUCLE, QUE ADEMÁS ES EL CODIGO DEL CARRO
        int contador = 1;
        // RECORREMOS LOS CARROS DE PORTATILES
        while (contador <= tamCarros) {
            // VALOR TRUE O FALSE SEGÚN SI ESTÁ RESERVADO O NO (FALSE RESERVADO, TRUE NO RESERVADO)
            boolean elementoSelect = carrosPortatiles.get(String.valueOf(contador));
            // COMPROBAMOS QUE LOS CARROS ESTÁN RESERVADOS O NO
            if (elementoSelect == true) {
                // VARIABLE QUE ALMACENA LOS CARROS DISPONIBLES
                numCarrosD++;
            } else {
                // VARIABLE QUE ALMACENA LOS CARROS ¡ NO DISPONIBLE !
                numCarrosND++;
            }
            contador++;
        }
        
        // CREAMOS EL OBJETO DEL FORMULARIO DE INICIO DE SESION Y LE PASO LAS VARIABLES CORRESPONDIENTES
        form_iniciar_sesion formInSession = new form_iniciar_sesion(usuariosRegistrados, usuariosAdministradores, carrosPortatiles, numCarrosD, numCarrosND);
        // OCULTO EL FORMULARIO ACTUAL
        this.setVisible(false);
        // MUESTRO EL FORMULARIO DEL OBJETO QUE HEMOS CREADO
        formInSession.setVisible(true);
    }//GEN-LAST:event_botonLoginActionPerformed

    private void botonCarrosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarrosDisponiblesActionPerformed
        int tamCarros = carrosPortatiles.size();
        // CONTADOR DEL BUCLE, QUE ADEMÁS ES EL CODIGO DEL CARRO
        int contador = 1;
        // RECORREMOS LOS CARROS DE PORTATILES
        while (contador <= tamCarros) {
            // VALOR TRUE O FALSE SEGÚN SI ESTÁ RESERVADO O NO (FALSE RESERVADO, TRUE NO RESERVADO)
            boolean elementoSelect = carrosPortatiles.get(String.valueOf(contador));
            // COMPROBAMOS QUE LOS CARROS ESTÁN RESERVADOS O NO
            if (elementoSelect == true) {
                // VARIABLE QUE ALMACENA LOS CARROS DISPONIBLES
                numCarrosD++;
            } else {
                // VARIABLE QUE ALMACENA LOS CARROS ¡ NO DISPONIBLE !
                numCarrosND++;
            }
            contador++;
        }
        int confirmar = JOptionPane.showConfirmDialog(null, "Hay un total de " + String.valueOf(numCarrosD) + " carros disponibles. ¿Quiéres reservar un carro? Inicie sesión.");
        if (confirmar != 0) {
            // NADA
        } else {
            form_iniciar_sesion formInSession = new form_iniciar_sesion(usuariosRegistrados, usuariosAdministradores, carrosPortatiles, numCarrosD, numCarrosND);
            this.setVisible(false);
            formInSession.setVisible(true);
        }
    }//GEN-LAST:event_botonCarrosDisponiblesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCarrosDisponibles;
    private javax.swing.JButton botonLogin;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
